select * from customer

-- total revenue generated by male vs female 
select gender, sum(purchase_amount) as total_revenue from customer group by gender;

-- which customer used a discout but still spent more tha the average purchase amount
select customer_id, purchase_amount from customer where  discount_applied ='Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

-- top 5 products with the highest average review rating
select item_purchased, avg(review_rating) as review_rating from customer group by item_purchased order by avg(review_rating) desc limit 5; 

-- compare the average purchase amounts between standard and express shipping
select shipping_type,  avg(purchase_amount) from customer where shipping_type in ('Standard','Express') group by shipping_type; 

-- compare average spend and total revenue  between subscribers and non-subscribers
select subscription_status,sum(purchase_amount) as total_revenue, round(avg(purchase_amount),2) as avg_spend from customer where  subscription_status in ('Yes', 'No') group by subscription_status;

-- which product have highest percentage of purchases with discount applied
-- two different ways to solve 
select item_purchased,  100 * count(*) filter(where discount_applied = 'Yes')/ count(*) as pct_of_purchase_after_disc from customer group by item_purchased order by pct_of_purchase_after_disc desc limit 5;
select item_purchased,(100 * sum(case when discount_applied ='Yes' then 1 else 0 end) / count(*)) as pct_of_purchase_after_disc from customer group by item_purchased order by pct_of_purchase_after_disc desc limit 5;

-- segment customers into New, Returning, and loyal based on their total no.of previous purchases and show the count of each segment
 --diff ways of solving
 select case 
 when (previous_purchases)=1 then 'new_customer' 
 when (previous_purchases)<11 and (previous_purchases)>1 then 'returning_customer' 
 else 'loyal_customer'
 end as customer_segment, count(*) as customer_count 
 from customer group by customer_segment order by customer_count desc;

with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases =1 then 'new_customer'
	when (previous_purchases)<11 and (previous_purchases)>1 then 'returning_customer' 
 	else 'loyal_customer'
 	end as customer_segment from customer
)
select customer_segment, count(*) as customer_count from customer_type group by customer_segment

-- top 3 most purchased products within each category
with item_counts as (
select  category, item_purchased, count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank 
from customer
group by category, item_purchased)

select item_rank, category, item_purchased, total_orders from item_counts where item_rank <=3;

-- are customers who repeat buyers also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers from customer where previous_purchases > 5 group by subscription_status;

-- revenue contribution of each age group 
select age_group, sum(purchase_amount) as total_revenue from customer group by age_group order by total_revenue desc;